[package]
name = "optionalize-macro"
version = "0.1.0"
edition = "2021"

[dependencies]
optionalize-core = {path = "../optionalize-core"}
syn = { version = "2.0.87", features = ["full"] }
quote = "1.0"
[lib]
proc-macro = true